### ISSUE TITLE
Published name

### ISSUE THREAD

**Issue by ShadowJonathan** [ShadowJonathan/dustls#4]
I'm still undecided as how to publish the crate on crates.io, I have already tried to get into contact with the crate owner of `dtls`, and if that comes through, I'll use that.

However, if it doesn't come through, I'd like an alternative name that can be instantly used. I've thought of `rustls-dtls`, but that would pledge and use the rustls namespace, which I am not 100% sure on yet.

Funny or clever names are appreciated though :D

**Comment by ShadowJonathan** [comment]
Some more ideas;
- `drustls`
- `rusdls`/`rusdtls`

**Comment by ShadowJonathan** [comment]
`dtlrs` is also a name.

I'm trying to find something quippy, like rustls is for tls, or quinn for QUIC.

**Comment by ShadowJonathan** [comment]
Spent a little while brainstorming about this, and I got the following;

- `redtls`
- `fraggdtls`
- `milldtls`
- `sandtls`
- `dustls`

I'm personally a big fan of "SanDTLS" and "DusTLS", both call to dust and sand particles, though the latter calls to rustls with its name.

**Comment by ShadowJonathan** [comment]
@ctz I really like the name "dustls", but since it comes so close to "rustls", i kinda feel like i have to request permission to use it, would it be alright if i used that name for this crate?

**Comment by ctz** [comment]
Thanks I appreciate the courtesy! I think that dustls has no potential to be confused with rustls, so I have no objection.
